-- Preserve the complete set of roles already shown by the refreshed public
-- talent page, while keeping any openings that editors have added in the CMS.
-- ON CONFLICT DO NOTHING deliberately preserves editorial changes.
with opening_seed (
  department_slug,
  opening_slug,
  title,
  subtitle,
  summary,
  image_url,
  duties,
  requirements,
  benefits,
  sort_order
) as (
  values
    (
      'home-care-team',
      'case-service-coordinator',
      '個案服務協調員',
      '家庭窗口',
      '協助家庭理解服務內容、建立照顧安排，讓需求、資源與實際執行能順利接起來。',
      '/assets/homepage-batch/family-consultation-clear.jpg',
      '["接洽家庭諮詢並整理需求","協助服務說明、派案前資料確認","追蹤服務開始後的家屬回饋"]'::jsonb,
      '["具客服、行政、長照或社福溝通經驗佳","文字紀錄清楚，能穩定追蹤細節","面對家屬焦慮時能保持同理與秩序"]'::jsonb,
      '["話術訓練","行政工具","主管陪談"]'::jsonb,
      30
    ),
    (
      'home-care-team',
      'home-reablement-partner',
      '居家護理復能夥伴',
      '專業協作',
      '與護理、復能與照顧團隊合作，協助長輩把日常動作重新練回生活裡。',
      '/assets/homepage-batch/13-rehab-walking-practice-fast.jpg',
      '["協助復能活動與安全陪伴","觀察長輩身體狀況並回報團隊","配合專業人員執行居家支持建議"]'::jsonb,
      '["具護理、復健、職能、照顧服務或運動指導背景佳","能重視安全、節奏與長輩意願","願意與跨專業團隊合作"]'::jsonb,
      '["專業督導","復能訓練","案例討論"]'::jsonb,
      40
    ),
    (
      'home-care-team',
      'home-admin-dispatch',
      '居家行政調度專員',
      '營運支援',
      '負責班表、服務紀錄、文件與行政追蹤，讓前線照顧能順利運作、不被雜事卡住。',
      '/assets/homepage-batch/04-admin-team-office-fast.jpg',
      '["協助排班、服務異動與資料整理","追蹤服務紀錄、文件與行政流程","支援督導與客服窗口回覆"]'::jsonb,
      '["熟悉文書、表格與資料整理","細心、穩定，能處理多項進度","具長照行政或客服經驗佳"]'::jsonb,
      '["行政訓練","流程模板","固定工時"]'::jsonb,
      50
    ),
    (
      'day-care-team',
      'day-care-activity-facilitator',
      '日照活動帶領員',
      '活動設計',
      '規劃健康促進、認知刺激、手作、音樂與社交活動，讓長輩白天有參與感與成就感。',
      '/assets/daycare-recruit-02-exercise-clear.jpg',
      '["設計與帶領日照團體活動","觀察活動反應並調整難度","整理活動紀錄、照片與家屬回饋素材"]'::jsonb,
      '["具活動帶領、社工、職能、教育或長照經驗佳","能掌握現場氣氛與長輩安全","願意把活動設計成可複製的課程模組"]'::jsonb,
      '["活動教材","課程共備","講師培力"]'::jsonb,
      40
    ),
    (
      'day-care-team',
      'day-care-nurse',
      '日照護理人員',
      '健康照護',
      '負責健康評估、用藥與身體狀況觀察，協助團隊把日常照顧做得更安全。',
      '/assets/daycare-detail-02-meal-fast.jpg',
      '["長輩健康狀況觀察、量測與紀錄","協助用藥提醒、傷口與慢病照護追蹤","與家屬、照服員與外部醫療資源溝通"]'::jsonb,
      '["具護理師或護士證照","熟悉長者照護、慢病管理或日照場域佳","能把專業資訊轉成團隊看得懂的照顧提醒"]'::jsonb,
      '["護理支援","案例討論","專業進修"]'::jsonb,
      50
    ),
    (
      'day-care-team',
      'day-care-case-manager',
      '日照個案管理員',
      '家庭窗口',
      '協助家庭完成服務說明、長輩適應、照顧計畫追蹤與家屬溝通，是中心與家庭之間的橋樑。',
      '/assets/daycare-detail-04-checkin-fast.jpg',
      '["接洽家庭諮詢並整理長輩需求","追蹤長輩適應狀況與服務目標","定期彙整家屬回饋與團隊照顧建議"]'::jsonb,
      '["具社工、長照、客服或個案管理經驗佳","擅長傾聽、紀錄與跨角色溝通","能在家庭焦慮時提供清楚流程與支持"]'::jsonb,
      '["溝通模板","督導陪談","個案會議"]'::jsonb,
      60
    ),
    (
      'day-care-team',
      'day-care-operations-admin',
      '日照行政營運專員',
      '營運支援',
      '處理出缺勤、交通、耗材、文件、課程與現場行政，讓日照中心每天穩定運作。',
      '/assets/daycare-detail-04-checkin-fast.jpg',
      '["協助中心行政、文件、物資與課表安排","追蹤出缺勤、交通接送與家屬通知","支援主管完成營運報表與品質資料"]'::jsonb,
      '["熟悉文書、表格與流程追蹤","細心穩定，能處理多項現場需求","具長照行政、課務或客服經驗佳"]'::jsonb,
      '["行政流程","固定工時","跨部門支援"]'::jsonb,
      70
    ),
    (
      'migrant-team',
      'care-skills-coach',
      '照顧技能實作教練',
      '實作訓練',
      '專注於移位、翻身、沐浴、用餐與安全照顧演練，讓學員不是只聽懂，而是真的做得出來。',
      '/assets/migrant-detail-02-transfer-fast.jpg',
      '["進行照顧動作示範、分組演練與姿勢修正","協助建立安全檢核表與實作評量","回報學員學習狀況與需要補強的技能"]'::jsonb,
      '["具照顧服務、護理、復健或實作教學經驗佳","熟悉身體力學與長者安全照顧原則","能細心觀察動作風險並即時提醒"]'::jsonb,
      '["實作教案","安全訓練","案例討論"]'::jsonb,
      50
    ),
    (
      'migrant-team',
      'cross-cultural-counselor',
      '跨文化溝通輔導員',
      '溝通支持',
      '協助移工、家庭與照顧團隊理解彼此需求，降低溝通誤會，讓照顧指令可以被正確執行。',
      '/assets/migrant-recruit-04-communication-fast.jpg',
      '["協助照顧情境溝通演練與用語整理","支援家庭照顧規則、禁忌與回報方式說明","收集學員困難並回饋課程設計"]'::jsonb,
      '["具移工服務、語言教學、社福、客服或跨文化工作經驗佳","能同理不同文化背景與家庭壓力","文字整理與口語表達清楚"]'::jsonb,
      '["溝通腳本","主管陪談","情境卡教材"]'::jsonb,
      60
    ),
    (
      'migrant-team',
      'training-course-admin',
      '培訓課務專員',
      '課務行政',
      '負責開課行政、學員資料、課程通知、簽到評量與結訓文件，讓每一堂課順利運作。',
      '/assets/quality-recruit-04-quality-meeting-clear.jpg',
      '["處理課程報名、通知、簽到與教材準備","整理學員資料、評量結果與結訓紀錄","支援講師、場地、物資與課後回饋追蹤"]'::jsonb,
      '["熟悉文書、表格與課務行政流程","細心穩定，能處理多項課程進度","具教育訓練、行政或長照課務經驗佳"]'::jsonb,
      '["課務流程","表單模板","固定工時"]'::jsonb,
      70
    ),
    (
      'migrant-team',
      'family-care-course-planner',
      '家庭照顧課程企劃',
      '內容企劃',
      '把家庭照顧常見問題整理成課程、懶人包與實作教材，協助家庭與移工建立共同照顧語言。',
      '/assets/migrant-detail-03-meal-fast.jpg',
      '["規劃照顧課程主題、教材架構與活動流程","整理照顧知識、圖卡、評量與課後提醒","與講師、督導、行政協作優化課程品質"]'::jsonb,
      '["具課程企劃、教材設計、長照或健康教育經驗佳","能把複雜知識轉成簡單可操作內容","重視使用者理解與實際照顧情境"]'::jsonb,
      '["教材素材庫","跨部門共備","企劃培訓"]'::jsonb,
      80
    ),
    (
      'quality-team',
      'internal-training-instructor',
      '內訓講師',
      '教育訓練',
      '帶領新人訓練與在職教育，把照顧倫理、服務流程、情境處理與紀錄回報教到能落地。',
      '/assets/quality-recruit-02-training-clear.jpg',
      '["規劃並執行新人訓練、在職教育與情境演練","依服務問題設計補強課程與測驗","追蹤學員學習成果與現場應用狀況"]'::jsonb,
      '["具照顧教學、護理、社工、督導或教育訓練經驗佳","表達清楚，能把複雜流程拆成好理解步驟","願意和前線團隊共同修正教材"]'::jsonb,
      '["講師培力","課程共備","教材素材庫"]'::jsonb,
      60
    ),
    (
      'quality-team',
      'learning-material-designer',
      '教材設計企劃',
      '內容設計',
      '把照顧知識、服務流程與案例整理成簡報、圖卡、手冊與線上教材，讓知識更容易被吸收。',
      '/assets/quality-detail-01-materials-fast.jpg',
      '["設計長照教材、流程圖、照顧圖卡與課程簡報","整理案例、FAQ 與標準作業說明","與講師、督導、行政協作更新教材版本"]'::jsonb,
      '["具教材設計、內容企劃、教育、長照或健康知識背景佳","能把文字、圖像與流程整理得清楚易懂","重視學習者視角與實際現場使用"]'::jsonb,
      '["設計模板","案例資料庫","跨部門共備"]'::jsonb,
      70
    ),
    (
      'quality-team',
      'service-auditor',
      '服務稽核人員',
      '稽核改善',
      '透過現場觀察、紀錄檢查與團隊訪談，協助服務單位發現風險、修正流程並維持品質。',
      '/assets/quality-recruit-04-quality-meeting-clear.jpg',
      '["執行服務流程、紀錄與現場品質檢核","整理稽核結果與改善追蹤表","用支持性的方式給予前線具體回饋"]'::jsonb,
      '["具長照服務、督導、品管、稽核或護理背景佳","能客觀觀察、清楚記錄並友善溝通","重視安全、倫理與服務一致性"]'::jsonb,
      '["稽核工具","主管陪同","改善會議"]'::jsonb,
      80
    ),
    (
      'quality-team',
      'quality-improvement-project-manager',
      '品質改善專案管理',
      '專案推進',
      '把服務問題、數據與跨部門需求整合成改善專案，讓品管不只是檢查，而是推動變好。',
      '/assets/quality-recruit-04-quality-meeting-clear.jpg',
      '["規劃品質改善專案、時程與追蹤指標","整合督導、行政、講師與前線回饋","製作改善報告、會議資料與成果追蹤"]'::jsonb,
      '["具專案管理、營運、品管或長照管理經驗佳","能整理資料、掌握進度並推動跨部門合作","喜歡把混亂問題變成清楚流程"]'::jsonb,
      '["專案模板","資料儀表板","管理培力"]'::jsonb,
      90
    ),
    (
      'admin-team',
      'hr-recruiter',
      '人資招募專員',
      '人才招募',
      '負責招募、面談安排、新人報到與員工關懷，協助歲悅找到願意長久投入照顧的夥伴。',
      '/assets/homepage-batch/orange-polo-supervisor-clear.jpg',
      '["發布職缺、履歷篩選、面談安排與錄取通知","協助新人報到、資料建檔與入職流程","追蹤新人適應狀況與部門人力需求"]'::jsonb,
      '["具人資、招募、行政或客服經驗佳","溝通親切、紀錄清楚，能穩定追蹤進度","認同長照服務，願意理解前線工作型態"]'::jsonb,
      '["招募模板","面談流程","新人關懷"]'::jsonb,
      70
    ),
    (
      'admin-team',
      'finance-admin',
      '財務行政專員',
      '財務文件',
      '負責請款、收支資料、發票憑證、報表整理與行政核對，讓公司營運數據穩定清楚。',
      '/assets/admin-recruit-02-operations-hires.jpg',
      '["整理收支、請款、發票、憑證與對帳資料","協助月報、專案報表與合約文件歸檔","追蹤付款時程、費用申請與行政核銷"]'::jsonb,
      '["具財務、會計、行政或出納經驗佳","細心、守時，對數字與文件有耐心","熟悉試算表與基本文書工具"]'::jsonb,
      '["報表格式","核銷流程","財務主管支援"]'::jsonb,
      80
    ),
    (
      'admin-team',
      'customer-service-general-affairs',
      '客服總務專員',
      '服務窗口',
      '承接電話、信箱、一般諮詢與總務事項，協助家庭、合作單位與內部團隊快速找到對的人。',
      '/assets/homepage-batch/family-consultation-clear.jpg',
      '["接聽電話、回覆信箱與初步分類需求","協助總務採購、文件收發與環境物資管理","追蹤諮詢案件、轉介窗口與回覆進度"]'::jsonb,
      '["具客服、總務、行政或服務窗口經驗佳","說明清楚、態度穩定，能面對焦急詢問","能整理資訊並確實追蹤到結案"]'::jsonb,
      '["回覆腳本","總務清單","窗口訓練"]'::jsonb,
      90
    ),
    (
      'admin-team',
      'investor-project-admin',
      '投資人與專案行政',
      '專案窗口',
      '支援投資人資料、合作提案、專案文件與會議進度，讓外部合作與內部執行有清楚節奏。',
      '/assets/admin-recruit-05-meeting-clear.jpg',
      '["整理投資人資料、簡報、會議紀錄與追蹤事項","協助合作提案、標案文件與專案時程管理","彙整各部門進度，製作對外與內部報告"]'::jsonb,
      '["具專案行政、企劃、投資人關係或秘書經驗佳","文字整理清楚，能掌握會議重點與時程","具保密意識與跨部門溝通能力"]'::jsonb,
      '["簡報模板","專案管理","主管共作"]'::jsonb,
      100
    )
)
insert into public.recruiting_openings (
  page_slug,
  department_id,
  opening_slug,
  title,
  subtitle,
  summary,
  employment_type,
  location,
  salary_text,
  capacity_label,
  image_url,
  duties,
  requirements,
  benefits,
  apply_button_text,
  apply_form_enabled,
  metadata,
  sort_order,
  is_featured,
  is_enabled,
  status,
  published_at
)
select
  'talent',
  department.id,
  seed.opening_slug,
  seed.title,
  seed.subtitle,
  seed.summary,
  '全職',
  case seed.department_slug
    when 'home-care-team' then '臺北、新北、桃園'
    when 'day-care-team' then '臺北 / 新北據點'
    when 'migrant-team' then '臺北 / 線上'
    else '臺北辦公室'
  end,
  '面議 / 依經驗核定',
  '1-2 名',
  seed.image_url,
  seed.duties,
  seed.requirements,
  seed.benefits,
  '申請應徵',
  true,
  '{"form_type":"recruiting","source":"public-talent-page-2026-07"}'::jsonb,
  seed.sort_order,
  false,
  true,
  'published',
  now()
from opening_seed seed
join public.recruiting_departments department
  on department.page_slug = 'talent'
 and department.department_slug = seed.department_slug
on conflict (page_slug, opening_slug) do nothing;
