-- Visual page editor: page-level drafts, atomic Owner review, and canonical
-- template fields. Existing ungrouped publish requests remain supported.

create table if not exists public.cms_change_sets (
  id uuid primary key default gen_random_uuid(),
  page_slug text not null,
  scope_key text not null references public.cms_content_areas(scope_key) on update cascade on delete restrict,
  title text not null,
  status text not null default 'draft',
  draft_payload jsonb not null default '{"version":1,"changes":[]}'::jsonb,
  requested_by uuid not null references public.profiles(id) on delete restrict,
  department_id uuid not null references public.departments(id) on delete restrict,
  submitted_at timestamptz,
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  reviewer_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint cms_change_sets_page_slug_format check (page_slug ~ '^[a-z0-9][a-z0-9-]*$'),
  constraint cms_change_sets_status_check check (status in ('draft', 'pending', 'approved', 'rejected', 'cancelled')),
  constraint cms_change_sets_payload_shape check (
    jsonb_typeof(draft_payload) = 'object'
    and jsonb_typeof(draft_payload->'changes') = 'array'
  )
);

create unique index if not exists cms_change_sets_one_draft_per_page_idx
on public.cms_change_sets(requested_by, page_slug)
where status = 'draft';

create index if not exists cms_change_sets_scope_status_idx
on public.cms_change_sets(scope_key, status, updated_at desc);

create index if not exists cms_change_sets_requester_idx
on public.cms_change_sets(requested_by, updated_at desc);

drop trigger if exists set_cms_change_sets_updated_at on public.cms_change_sets;
create trigger set_cms_change_sets_updated_at
before update on public.cms_change_sets
for each row execute function public.set_updated_at();

alter table public.publish_requests
  add column if not exists change_set_id uuid references public.cms_change_sets(id) on delete set null;

create index if not exists publish_requests_change_set_idx
on public.publish_requests(change_set_id, status, requested_at desc);

-- Keep a recovery copy before collapsing the legacy service_hero records.
create table if not exists private.visual_editor_migration_backups (
  id bigint generated by default as identity primary key,
  migration_key text not null,
  source_table text not null,
  row_snapshot jsonb not null,
  backed_up_at timestamptz not null default now()
);

insert into private.visual_editor_migration_backups (migration_key, source_table, row_snapshot)
select
  '20260720153836_template_field_deduplication',
  'page_template_fields',
  to_jsonb(source)
from public.page_template_fields source
where source.template_key = 'service_hero'
  and exists (
    select 1
    from public.page_template_fields canonical
    where canonical.page_slug = source.page_slug
      and canonical.template_key = 'service_page'
      and canonical.field_key = source.field_key
  )
  and not exists (
    select 1
    from private.visual_editor_migration_backups backup
    where backup.migration_key = '20260720153836_template_field_deduplication'
      and backup.row_snapshot->>'id' = source.id::text
  );

update public.page_template_fields canonical
set
  text_value = case
    when nullif(btrim(canonical.text_value), '') is null then legacy.text_value
    else canonical.text_value
  end,
  number_value = coalesce(canonical.number_value, legacy.number_value),
  boolean_value = coalesce(canonical.boolean_value, legacy.boolean_value),
  image_id = coalesce(canonical.image_id, legacy.image_id),
  json_value = case
    when canonical.json_value is null or canonical.json_value = '{}'::jsonb then coalesce(legacy.json_value, '{}'::jsonb)
    else canonical.json_value
  end,
  help_text = coalesce(nullif(canonical.help_text, ''), legacy.help_text),
  updated_at = now()
from public.page_template_fields legacy
where canonical.page_slug = legacy.page_slug
  and canonical.field_key = legacy.field_key
  and canonical.template_key = 'service_page'
  and legacy.template_key = 'service_hero';

delete from public.page_template_fields legacy
where legacy.template_key = 'service_hero'
  and exists (
    select 1
    from public.page_template_fields canonical
    where canonical.page_slug = legacy.page_slug
      and canonical.template_key = 'service_page'
      and canonical.field_key = legacy.field_key
  );

create unique index if not exists page_template_fields_page_field_unique_idx
on public.page_template_fields(page_slug, field_key);

update public.cms_content_areas
set admin_path = case scope_key
  when 'page:home' then '/admin/visual-editor?page=home'
  when 'service:home-care' then '/admin/visual-editor?page=home-care'
  when 'service:day-care' then '/admin/visual-editor?page=day-care'
  when 'service:community' then '/admin/visual-editor?page=community'
  when 'service:nursing' then '/admin/visual-editor?page=nursing'
  when 'service:migrant-training' then '/admin/visual-editor?page=migrant-training'
  when 'service:quality' then '/admin/visual-editor?page=quality'
  when 'service:software' then '/admin/visual-editor?page=software'
  when 'recruiting:talent' then '/admin/visual-editor?page=talent'
  else admin_path
end,
updated_at = now()
where scope_key in (
  'page:home',
  'service:home-care',
  'service:day-care',
  'service:community',
  'service:nursing',
  'service:migrant-training',
  'service:quality',
  'service:software',
  'recruiting:talent'
);

create or replace function private.normalize_cms_snapshot(row_snapshot jsonb)
returns jsonb
language sql
immutable
set search_path = public, private
as $$
  select coalesce(row_snapshot, 'null'::jsonb)
    - array['created_at', 'created_by', 'updated_at', 'updated_by', 'published_at']::text[]
$$;

create or replace function private.validate_cms_change_payload(
  target_page_slug text,
  target_scope_key text,
  payload jsonb
)
returns void
language plpgsql
stable
security definer
set search_path = public, private
as $$
declare
  item jsonb;
  item_table text;
  item_id uuid;
  item_scope text;
  item_action text;
  allowed_tables constant text[] := array[
    'pages', 'page_sections', 'content_modules', 'page_template_fields',
    'recruiting_pages', 'recruiting_departments', 'recruiting_openings'
  ];
begin
  if target_page_slug is null
    or target_scope_key is null
    or private.scope_for_page_slug(target_page_slug) is distinct from target_scope_key
  then
    raise exception 'The requested page is not mapped to a responsibility scope.';
  end if;

  if jsonb_typeof(payload) <> 'object'
    or coalesce((payload->>'version')::integer, 0) <> 1
    or jsonb_typeof(payload->'changes') <> 'array'
    or jsonb_array_length(payload->'changes') > 250
  then
    raise exception 'The page draft payload is invalid.';
  end if;

  for item in select value from jsonb_array_elements(payload->'changes')
  loop
    item_table := item->>'entity_table';
    item_action := coalesce(item->>'change_action', 'upsert');

    begin
      item_id := nullif(item->>'entity_id', '')::uuid;
    exception when invalid_text_representation then
      raise exception 'A page draft contains an invalid record id.';
    end;

    if item_table is null
      or not (item_table = any(allowed_tables))
      or item_id is null
      or item_action not in ('upsert', 'delete')
    then
      raise exception 'A page draft contains an unsupported change.';
    end if;

    if item_action = 'upsert' and jsonb_typeof(item->'proposed_snapshot') <> 'object' then
      raise exception 'Every updated record must include its proposed content.';
    end if;

    if item_action = 'delete' and jsonb_typeof(item->'base_snapshot') <> 'object' then
      raise exception 'Every deleted record must include its original content.';
    end if;

    if item_action = 'upsert'
      and nullif(item->'proposed_snapshot'->>'id', '')::uuid is distinct from item_id
    then
      raise exception 'A proposed record id does not match its page draft.';
    end if;

    item_scope := private.scope_for_entity_snapshot(
      item_table,
      coalesce(item->'proposed_snapshot', item->'base_snapshot')
    );

    if item_scope is distinct from target_scope_key then
      raise exception 'A page draft contains content owned by another department.';
    end if;
  end loop;
end;
$$;

create or replace function public.save_cms_change_set(
  target_page_slug text,
  draft_payload jsonb,
  draft_title text default null
)
returns public.cms_change_sets
language plpgsql
security definer
set search_path = public, private
as $$
declare
  current_profile uuid;
  target_scope text;
  target_department uuid;
  existing_draft public.cms_change_sets;
  result_row public.cms_change_sets;
begin
  if auth.uid() is null then
    raise exception 'You must be signed in to save a page draft.';
  end if;

  current_profile := private.current_profile_id();
  target_scope := private.scope_for_page_slug(target_page_slug);
  target_department := private.department_for_scope(target_scope);

  if current_profile is null or target_scope is null or target_department is null then
    raise exception 'This page is not available in the visual editor.';
  end if;
  if not private.can_edit_content_scope(target_scope) then
    raise exception 'You cannot edit a page owned by another department.';
  end if;

  perform private.validate_cms_change_payload(target_page_slug, target_scope, draft_payload);

  select *
  into existing_draft
  from public.cms_change_sets change_set
  where change_set.requested_by = current_profile
    and change_set.page_slug = target_page_slug
    and change_set.status = 'draft'
  order by change_set.updated_at desc
  limit 1
  for update;

  if found then
    update public.cms_change_sets
    set
      title = coalesce(nullif(btrim(draft_title), ''), title),
      scope_key = target_scope,
      department_id = target_department,
      draft_payload = draft_payload,
      reviewer_note = null,
      reviewed_by = null,
      reviewed_at = null
    where id = existing_draft.id
    returning * into result_row;
  else
    insert into public.cms_change_sets (
      page_slug,
      scope_key,
      title,
      draft_payload,
      requested_by,
      department_id
    )
    values (
      target_page_slug,
      target_scope,
      coalesce(nullif(btrim(draft_title), ''), target_page_slug || ' 頁面修改'),
      draft_payload,
      current_profile,
      target_department
    )
    returning * into result_row;
  end if;

  return result_row;
end;
$$;

create or replace function public.submit_cms_change_set(change_set_id uuid)
returns public.cms_change_sets
language plpgsql
security definer
set search_path = public, private
as $$
declare
  current_profile uuid;
  change_set public.cms_change_sets;
  item jsonb;
  current_snapshot jsonb;
  item_id uuid;
  item_table text;
  item_action text;
  item_target_status public.cms_publish_status;
  result_row public.cms_change_sets;
begin
  if auth.uid() is null then
    raise exception 'You must be signed in to submit a page draft.';
  end if;

  current_profile := private.current_profile_id();
  select *
  into change_set
  from public.cms_change_sets
  where id = change_set_id
  for update;

  if not found then
    raise exception 'Page draft not found.';
  end if;
  if change_set.status <> 'draft' then
    raise exception 'Only a saved draft can be submitted.';
  end if;
  if change_set.requested_by is distinct from current_profile
    and not private.current_profile_is_owner()
  then
    raise exception 'You can only submit your own page draft.';
  end if;
  if not private.can_edit_content_scope(change_set.scope_key) then
    raise exception 'You no longer have permission to submit this page.';
  end if;

  perform private.validate_cms_change_payload(
    change_set.page_slug,
    change_set.scope_key,
    change_set.draft_payload
  );

  if jsonb_array_length(change_set.draft_payload->'changes') = 0 then
    raise exception 'There are no page changes to submit.';
  end if;

  for item in select value from jsonb_array_elements(change_set.draft_payload->'changes')
  loop
    item_table := item->>'entity_table';
    item_id := (item->>'entity_id')::uuid;
    item_action := coalesce(item->>'change_action', 'upsert');
    item_target_status := coalesce(nullif(item->>'target_status', '')::public.cms_publish_status, 'published');

    execute format(
      'select to_jsonb(entity_row) from public.%I entity_row where id = $1',
      item_table
    )
    into current_snapshot
    using item_id;

    if item->'base_snapshot' is null or item->'base_snapshot' = 'null'::jsonb then
      if current_snapshot is not null then
        raise exception 'This page was updated by someone else. Refresh before submitting.';
      end if;
    elsif current_snapshot is null
      or private.normalize_cms_snapshot(current_snapshot)
        is distinct from private.normalize_cms_snapshot(item->'base_snapshot')
    then
      raise exception 'This page was updated by someone else. Refresh before submitting.';
    end if;

    insert into public.publish_requests (
      entity_table,
      entity_id,
      entity_title,
      target_status,
      status,
      request_note,
      requested_by,
      scope_key,
      department_id,
      base_snapshot,
      proposed_snapshot,
      change_action,
      change_set_id
    )
    values (
      item_table,
      item_id,
      coalesce(nullif(item->>'entity_title', ''), private.publish_request_title(coalesce(item->'proposed_snapshot', item->'base_snapshot'), item_table)),
      item_target_status,
      'pending',
      coalesce(nullif(item->>'request_note', ''), '整頁修改已送交執行長確認。'),
      current_profile,
      change_set.scope_key,
      change_set.department_id,
      item->'base_snapshot',
      item->'proposed_snapshot',
      item_action,
      change_set.id
    );
  end loop;

  update public.cms_change_sets
  set status = 'pending', submitted_at = now()
  where id = change_set.id
  returning * into result_row;

  insert into public.admin_activity_logs (
    profile_id, action, entity_table, entity_id, message, metadata, scope_key, department_id
  )
  values (
    current_profile,
    'cms_change_set_submitted',
    'cms_change_sets',
    change_set.id,
    change_set.title,
    jsonb_build_object(
      'page_slug', change_set.page_slug,
      'change_count', jsonb_array_length(change_set.draft_payload->'changes')
    ),
    change_set.scope_key,
    change_set.department_id
  );

  return result_row;
end;
$$;

create or replace function public.review_cms_change_set(
  change_set_id uuid,
  next_status text,
  reviewer_note text default null
)
returns public.cms_change_sets
language plpgsql
security definer
set search_path = public, private
as $$
declare
  change_set public.cms_change_sets;
  request_row public.publish_requests;
  current_snapshot jsonb;
  affected_rows integer;
  processed_count integer := 0;
  result_row public.cms_change_sets;
begin
  if next_status not in ('approved', 'rejected') then
    raise exception 'A page draft can only be approved or rejected.';
  end if;
  if not private.current_profile_is_owner() then
    raise exception 'Only the Owner or chief executive can review a page draft.';
  end if;
  if next_status = 'rejected' and nullif(btrim($3), '') is null then
    raise exception 'A rejection reason is required.';
  end if;

  select *
  into change_set
  from public.cms_change_sets
  where id = change_set_id
  for update;

  if not found then
    raise exception 'Page draft not found.';
  end if;
  if change_set.status <> 'pending' then
    raise exception 'Only a pending page draft can be reviewed.';
  end if;

  for request_row in
    select *
    from public.publish_requests request
    where request.change_set_id = change_set.id
      and request.status = 'pending'
    order by request.requested_at, request.id
    for update
  loop
    processed_count := processed_count + 1;

    if next_status = 'approved' then
      execute format(
        'select to_jsonb(entity_row) from public.%I entity_row where id = $1',
        request_row.entity_table
      )
      into current_snapshot
      using request_row.entity_id;

      if request_row.base_snapshot is null then
        if current_snapshot is not null then
          raise exception 'The live page changed after submission. Ask the editor to refresh.';
        end if;
      elsif current_snapshot is null
        or private.normalize_cms_snapshot(current_snapshot)
          is distinct from private.normalize_cms_snapshot(request_row.base_snapshot)
      then
        raise exception 'The live page changed after submission. Ask the editor to refresh.';
      end if;

      if request_row.change_action = 'delete' then
        execute format('delete from public.%I where id = $1', request_row.entity_table)
        using request_row.entity_id;
        get diagnostics affected_rows = row_count;
        if affected_rows <> 1 then
          raise exception 'A page record no longer exists.';
        end if;
      else
        perform private.apply_content_snapshot(
          request_row.entity_table,
          request_row.entity_id,
          request_row.proposed_snapshot,
          request_row.target_status::text
        );
      end if;
    end if;

    update public.publish_requests
    set
      status = next_status,
      review_note = $3,
      reviewed_by = private.current_profile_id(),
      reviewed_at = now()
    where id = request_row.id;
  end loop;

  if processed_count = 0 then
    raise exception 'This page draft has no pending review items.';
  end if;

  update public.cms_change_sets
  set
    status = next_status,
    reviewer_note = $3,
    reviewed_by = private.current_profile_id(),
    reviewed_at = now()
  where id = change_set.id
  returning * into result_row;

  insert into public.admin_activity_logs (
    profile_id, action, entity_table, entity_id, message, metadata, scope_key, department_id
  )
  values (
    private.current_profile_id(),
    'cms_change_set_' || next_status,
    'cms_change_sets',
    change_set.id,
    coalesce(nullif(btrim($3), ''), change_set.title),
    jsonb_build_object(
      'page_slug', change_set.page_slug,
      'change_count', processed_count
    ),
    change_set.scope_key,
    change_set.department_id
  );

  return result_row;
end;
$$;

alter table public.cms_change_sets enable row level security;

drop policy if exists "Department users can view page change sets" on public.cms_change_sets;
create policy "Department users can view page change sets"
on public.cms_change_sets
for select
to authenticated
using (
  requested_by = (select private.current_profile_id())
  or (select private.current_profile_is_owner())
  or (select private.can_view_content_scope(scope_key))
);

drop policy if exists "Editors can create page change sets" on public.cms_change_sets;
create policy "Editors can create page change sets"
on public.cms_change_sets
for insert
to authenticated
with check (
  requested_by = (select private.current_profile_id())
  and status = 'draft'
  and (select private.can_edit_content_scope(scope_key))
);

drop policy if exists "Editors can update their page drafts" on public.cms_change_sets;
create policy "Editors can update their page drafts"
on public.cms_change_sets
for update
to authenticated
using (
  (requested_by = (select private.current_profile_id()) and status = 'draft')
  or (select private.current_profile_is_owner())
)
with check (
  (requested_by = (select private.current_profile_id()) and (select private.can_edit_content_scope(scope_key)))
  or (select private.current_profile_is_owner())
);

drop policy if exists "Editors can delete their page drafts" on public.cms_change_sets;
create policy "Editors can delete their page drafts"
on public.cms_change_sets
for delete
to authenticated
using (
  (requested_by = (select private.current_profile_id()) and status = 'draft')
  or (select private.current_profile_is_owner())
);

grant select, insert, update, delete on public.cms_change_sets to authenticated;
grant select, insert, update, delete on public.cms_change_sets to service_role;

revoke all on private.visual_editor_migration_backups from public, anon, authenticated;
grant select on private.visual_editor_migration_backups to service_role;

revoke all on function private.normalize_cms_snapshot(jsonb) from public, anon;
revoke all on function private.validate_cms_change_payload(text, text, jsonb) from public, anon;
revoke all on function public.save_cms_change_set(text, jsonb, text) from public, anon;
revoke all on function public.submit_cms_change_set(uuid) from public, anon;
revoke all on function public.review_cms_change_set(uuid, text, text) from public, anon;

grant execute on function public.save_cms_change_set(text, jsonb, text) to authenticated, service_role;
grant execute on function public.submit_cms_change_set(uuid) to authenticated, service_role;
grant execute on function public.review_cms_change_set(uuid, text, text) to authenticated, service_role;

comment on table public.cms_change_sets is 'Versioned page-level drafts used by the visual CMS editor.';
comment on column public.publish_requests.change_set_id is 'Groups legacy row-level publish requests into one atomic page review.';
