-- Align talent recruiting openings with the current 104 job list.
-- Keep old CMS rows for history, but remove them from the public talent page.

with target_openings (
  department_slug,
  opening_slug,
  title,
  subtitle,
  summary,
  employment_type,
  location,
  salary_text,
  capacity_label,
  image_url,
  duties,
  requirements,
  benefits,
  sort_order,
  is_featured,
  published_at
) as (
  values
    (
      'home-care-team',
      'taipei-shilin-home-caregiver',
      '臺北市居家照顧服務員（士林區）',
      '居服員',
      '在臺北市士林區到宅服務，提供身體照顧、生活支持、陪伴與服務紀錄，協助家庭把日常照顧接穩。',
      '全職 / 兼職',
      '臺北市士林區',
      '時薪 230-420 元',
      '持續招募',
      '/assets/recruit-home-care-worker-fast.jpg',
      '["依照顧計畫到宅提供身體照顧、備餐、家務、陪同外出或陪同就醫等支持","完成服務紀錄、異常回報與家屬溝通，讓督導能即時掌握服務狀況","配合督導安排排班、調班、教育訓練與服務品質追蹤"]'::jsonb,
      '["具照顧服務員訓練結業證明或長照小卡；有居家照顧經驗佳","能守時、重視安全與長輩尊嚴，願意照著服務計畫穩定執行","可配合服務區域排班，並使用手機或表單完成服務紀錄"]'::jsonb,
      '["BA 碼拆帳","AA 碼拆帳","缺工獎勵可申請","公發工作包","免費長照課程"]'::jsonb,
      10,
      true,
      '2026-07-08 00:00:00+08'::timestamptz
    ),
    (
      'home-care-team',
      'taipei-beitou-home-caregiver',
      '臺北市居家照顧服務員（北投區）',
      '居服員',
      '在臺北市北投區到宅服務，提供身體照顧、生活支持、陪伴與服務紀錄，協助家庭把日常照顧接穩。',
      '全職 / 兼職',
      '臺北市北投區',
      '時薪 230-420 元',
      '持續招募',
      '/assets/recruit-home-care-worker-fast.jpg',
      '["依照顧計畫到宅提供身體照顧、備餐、家務、陪同外出或陪同就醫等支持","完成服務紀錄、異常回報與家屬溝通，讓督導能即時掌握服務狀況","配合督導安排排班、調班、教育訓練與服務品質追蹤"]'::jsonb,
      '["具照顧服務員訓練結業證明或長照小卡；有居家照顧經驗佳","能守時、重視安全與長輩尊嚴，願意照著服務計畫穩定執行","可配合服務區域排班，並使用手機或表單完成服務紀錄"]'::jsonb,
      '["BA 碼拆帳","AA 碼拆帳","缺工獎勵可申請","公發工作包","免費長照課程"]'::jsonb,
      20,
      false,
      '2026-07-08 00:00:00+08'::timestamptz
    ),
    (
      'home-care-team',
      'taipei-nangang-home-caregiver',
      '臺北市居家照顧服務員（南港區）',
      '居服員',
      '在臺北市南港區到宅服務，提供身體照顧、生活支持、陪伴與服務紀錄，協助家庭把日常照顧接穩。',
      '全職 / 兼職',
      '臺北市南港區',
      '時薪 230-420 元',
      '持續招募',
      '/assets/recruit-home-care-worker-fast.jpg',
      '["依照顧計畫到宅提供身體照顧、備餐、家務、陪同外出或陪同就醫等支持","完成服務紀錄、異常回報與家屬溝通，讓督導能即時掌握服務狀況","配合督導安排排班、調班、教育訓練與服務品質追蹤"]'::jsonb,
      '["具照顧服務員訓練結業證明或長照小卡；有居家照顧經驗佳","能守時、重視安全與長輩尊嚴，願意照著服務計畫穩定執行","可配合服務區域排班，並使用手機或表單完成服務紀錄"]'::jsonb,
      '["BA 碼拆帳","AA 碼拆帳","缺工獎勵可申請","公發工作包","免費長照課程"]'::jsonb,
      30,
      false,
      '2026-07-08 00:00:00+08'::timestamptz
    ),
    (
      'home-care-team',
      'new-taipei-zhonghe-home-caregiver',
      '新北市居家照顧服務員（中和區）',
      '居服員',
      '在新北市中和區到宅服務，提供身體照顧、生活支持、陪伴與服務紀錄，協助家庭把日常照顧接穩。',
      '全職 / 兼職',
      '新北市中和區',
      '時薪 235-420 元',
      '持續招募',
      '/assets/recruit-home-care-worker-fast.jpg',
      '["依照顧計畫到宅提供身體照顧、備餐、家務、陪同外出或陪同就醫等支持","完成服務紀錄、異常回報與家屬溝通，讓督導能即時掌握服務狀況","配合督導安排排班、調班、教育訓練與服務品質追蹤"]'::jsonb,
      '["具照顧服務員訓練結業證明或長照小卡；有居家照顧經驗佳","能守時、重視安全與長輩尊嚴，願意照著服務計畫穩定執行","可配合服務區域排班，並使用手機或表單完成服務紀錄"]'::jsonb,
      '["BA 碼拆帳","AA 碼拆帳","缺工獎勵可申請","公發工作包","免費長照課程"]'::jsonb,
      40,
      false,
      '2026-07-08 00:00:00+08'::timestamptz
    ),
    (
      'home-care-team',
      'new-taipei-yonghe-home-caregiver',
      '新北市居家照顧服務員（永和區）',
      '居服員',
      '在新北市永和區到宅服務，提供身體照顧、生活支持、陪伴與服務紀錄，協助家庭把日常照顧接穩。',
      '全職 / 兼職',
      '新北市永和區',
      '時薪 235-420 元',
      '持續招募',
      '/assets/recruit-home-care-worker-fast.jpg',
      '["依照顧計畫到宅提供身體照顧、備餐、家務、陪同外出或陪同就醫等支持","完成服務紀錄、異常回報與家屬溝通，讓督導能即時掌握服務狀況","配合督導安排排班、調班、教育訓練與服務品質追蹤"]'::jsonb,
      '["具照顧服務員訓練結業證明或長照小卡；有居家照顧經驗佳","能守時、重視安全與長輩尊嚴，願意照著服務計畫穩定執行","可配合服務區域排班，並使用手機或表單完成服務紀錄"]'::jsonb,
      '["BA 碼拆帳","AA 碼拆帳","缺工獎勵可申請","公發工作包","免費長照課程"]'::jsonb,
      50,
      false,
      '2026-07-08 00:00:00+08'::timestamptz
    ),
    (
      'home-care-team',
      'new-taipei-xindian-home-caregiver',
      '新北市居家照顧服務員（新店區）',
      '居服員',
      '在新北市新店區到宅服務，提供身體照顧、生活支持、陪伴與服務紀錄，協助家庭把日常照顧接穩。',
      '全職 / 兼職',
      '新北市新店區',
      '時薪 235-420 元',
      '持續招募',
      '/assets/recruit-home-care-worker-fast.jpg',
      '["依照顧計畫到宅提供身體照顧、備餐、家務、陪同外出或陪同就醫等支持","完成服務紀錄、異常回報與家屬溝通，讓督導能即時掌握服務狀況","配合督導安排排班、調班、教育訓練與服務品質追蹤"]'::jsonb,
      '["具照顧服務員訓練結業證明或長照小卡；有居家照顧經驗佳","能守時、重視安全與長輩尊嚴，願意照著服務計畫穩定執行","可配合服務區域排班，並使用手機或表單完成服務紀錄"]'::jsonb,
      '["BA 碼拆帳","AA 碼拆帳","缺工獎勵可申請","公發工作包","免費長照課程"]'::jsonb,
      60,
      false,
      '2026-07-08 00:00:00+08'::timestamptz
    ),
    (
      'home-care-team',
      'new-taipei-tamsui-home-caregiver',
      '新北市居家照顧服務員（淡水區）',
      '居服員',
      '在新北市淡水區到宅服務，提供身體照顧、生活支持、陪伴與服務紀錄，協助家庭把日常照顧接穩。',
      '全職 / 兼職',
      '新北市淡水區',
      '時薪 235-420 元',
      '持續招募',
      '/assets/recruit-home-care-worker-fast.jpg',
      '["依照顧計畫到宅提供身體照顧、備餐、家務、陪同外出或陪同就醫等支持","完成服務紀錄、異常回報與家屬溝通，讓督導能即時掌握服務狀況","配合督導安排排班、調班、教育訓練與服務品質追蹤"]'::jsonb,
      '["具照顧服務員訓練結業證明或長照小卡；有居家照顧經驗佳","能守時、重視安全與長輩尊嚴，願意照著服務計畫穩定執行","可配合服務區域排班，並使用手機或表單完成服務紀錄"]'::jsonb,
      '["BA 碼拆帳","AA 碼拆帳","缺工獎勵可申請","公發工作包","免費長照課程"]'::jsonb,
      70,
      false,
      '2026-07-08 00:00:00+08'::timestamptz
    ),
    (
      'home-care-team',
      'taoyuan-dayuan-home-caregiver',
      '桃園市居家照顧服務員（大園區）',
      '居服員',
      '在桃園市大園區到宅服務，提供身體照顧、生活支持、陪伴與服務紀錄，協助家庭把日常照顧接穩。',
      '全職 / 兼職',
      '桃園市大園區',
      '時薪 235-420 元',
      '持續招募',
      '/assets/recruit-home-care-worker-fast.jpg',
      '["依照顧計畫到宅提供身體照顧、備餐、家務、陪同外出或陪同就醫等支持","完成服務紀錄、異常回報與家屬溝通，讓督導能即時掌握服務狀況","配合督導安排排班、調班、教育訓練與服務品質追蹤"]'::jsonb,
      '["具照顧服務員訓練結業證明或長照小卡；有居家照顧經驗佳","能守時、重視安全與長輩尊嚴，願意照著服務計畫穩定執行","可配合服務區域排班，並使用手機或表單完成服務紀錄"]'::jsonb,
      '["BA 碼拆帳","AA 碼拆帳","缺工獎勵可申請","公發工作包","免費長照課程"]'::jsonb,
      80,
      false,
      '2026-07-08 00:00:00+08'::timestamptz
    ),
    (
      'home-care-team',
      'taoyuan-luzhu-home-caregiver',
      '桃園市居家照顧服務員（蘆竹區）',
      '居服員',
      '在桃園市蘆竹區到宅服務，提供身體照顧、生活支持、陪伴與服務紀錄，協助家庭把日常照顧接穩。',
      '全職 / 兼職',
      '桃園市蘆竹區',
      '時薪 235-420 元',
      '持續招募',
      '/assets/recruit-home-care-worker-fast.jpg',
      '["依照顧計畫到宅提供身體照顧、備餐、家務、陪同外出或陪同就醫等支持","完成服務紀錄、異常回報與家屬溝通，讓督導能即時掌握服務狀況","配合督導安排排班、調班、教育訓練與服務品質追蹤"]'::jsonb,
      '["具照顧服務員訓練結業證明或長照小卡；有居家照顧經驗佳","能守時、重視安全與長輩尊嚴，願意照著服務計畫穩定執行","可配合服務區域排班，並使用手機或表單完成服務紀錄"]'::jsonb,
      '["BA 碼拆帳","AA 碼拆帳","缺工獎勵可申請","公發工作包","免費長照課程"]'::jsonb,
      90,
      false,
      '2026-07-08 00:00:00+08'::timestamptz
    ),
    (
      'day-care-team',
      'wanhua-day-care-caregiver',
      '萬華日照中心照顧服務員',
      '日照照服員',
      '在萬華日照中心陪伴長輩完成活動、餐食、休息與生活照顧，讓白天作息安全、有節奏。',
      '全職',
      '臺北市萬華區',
      '月薪 33,000-35,000 元',
      '1-2 名',
      '/assets/daycare-recruit-02-exercise-clear.jpg',
      '["協助日照長輩活動參與、用餐、如廁、休息與日常生活支持","完成服務紀錄、交班、異常觀察與家屬或團隊回報","配合護理、社工、督導執行照顧計畫與中心活動"]'::jsonb,
      '["具照顧服務員訓練結業證明佳","能主動觀察長輩狀態，重視安全、尊嚴與團隊交班","喜歡團體照顧場域，願意配合中心固定作息與活動安排"]'::jsonb,
      '["月薪制","新人帶教","缺工獎勵可申請","日照活動訓練"]'::jsonb,
      100,
      true,
      '2026-07-08 00:00:00+08'::timestamptz
    ),
    (
      'home-care-team',
      'taipei-home-care-supervisor',
      '臺北市居家服務督導員',
      '居服督導',
      '負責台北居家服務派案、品質追蹤、家訪電訪、照服員支持與補助核銷資料，讓服務穩定接上家庭需求。',
      '全職',
      '臺北市士林區',
      '月薪 38,000-42,000 元',
      '1-2 名',
      '/assets/recruit-home-care-supervisor-fast.jpg',
      '["安排居家服務個案、照服員媒合、服務異動與品質追蹤","定期家訪或電訪，處理家屬回饋、服務問題與異常狀況","支援照服員培訓、服務紀錄、評鑑資料與內部品質管理"]'::jsonb,
      '["具居家服務督導、社工、護理或長照相關背景佳","熟悉長照 2.0、BA 碼、照顧計畫與長照系統操作尤佳","能清楚溝通並在家屬、照服員、照管中心與 A 單位之間協調"]'::jsonb,
      '["保障月薪","業績獎金","督導培訓","開發獎金"]'::jsonb,
      110,
      true,
      '2026-07-08 00:00:00+08'::timestamptz
    ),
    (
      'migrant-team',
      'filipino-social-marketing-specialist',
      '全職社群行銷專員（菲律賓）',
      '菲律賓社群',
      '經營菲律賓語系社群與短影音內容，把照顧技能、工作故事與活動資訊轉成移工社群看得懂的內容。',
      '全職',
      '新北市新莊區',
      '月薪 35,000-38,000 元',
      '1 名',
      '/assets/migrant-recruit-04-communication-fast.jpg',
      '["經營 TikTok、Facebook、Instagram 等菲律賓語系社群，規劃貼文與短影音","協助拍攝剪輯 Reels、Shorts、照顧教學、工作故事與活動素材","把中文照顧 SOP、活動訊息與客服回覆轉成菲律賓社群可理解的溝通內容"]'::jsonb,
      '["具 1 年以上社群、內容、行銷或跨文化溝通經驗佳","熟悉菲律賓移工社群語境，能掌握熱門議題與互動方式","可與課務、行銷、客服與現場團隊協作，穩定產出內容"]'::jsonb,
      '["社群內容企劃","短影音製作","跨文化培訓","活動支援"]'::jsonb,
      120,
      true,
      '2026-07-08 00:00:00+08'::timestamptz
    ),
    (
      'migrant-team',
      'migrant-training-event-planner',
      '活動企劃專員',
      '移工培訓活動',
      '規劃移工培訓課程、節慶活動、交流活動與多語教材，把照顧技能訓練做成可追蹤的學習流程。',
      '全職',
      '新北市新莊區',
      '月薪 38,000-42,000 元',
      '1 名',
      '/assets/quality-recruit-04-quality-meeting-clear.jpg',
      '["規劃移工照顧培訓課程、節慶活動、交流活動與壓力支持工作坊","協調講師、教材、場地、預算、學習紀錄與服務品質回饋","支援多語教材、SOP、政府或 NGO 合作提案與補助報告"]'::jsonb,
      '["具 3 年以上活動企劃、教育訓練、課務或長照相關經驗佳","能掌握預算、時程、跨單位合作與活動現場執行細節","對移工培訓、長照服務與跨文化溝通有興趣"]'::jsonb,
      '["活動企劃","課務流程","多語教材","外部合作"]'::jsonb,
      130,
      false,
      '2026-07-08 00:00:00+08'::timestamptz
    ),
    (
      'admin-team',
      'social-media-marketing-planner',
      '社群媒體行銷企劃',
      '品牌行銷',
      '規劃 Facebook、Instagram、LINE、YouTube 等社群內容，讓長照服務、人才招募與品牌故事被穩定看見。',
      '全職',
      '臺北市信義區',
      '月薪 36,000-42,000 元',
      '1 名',
      '/assets/admin-recruit-05-meeting-clear.jpg',
      '["規劃社群策略、內容月曆、貼文文案、活動素材與影音腳本","與設計、影音、營運團隊協作，追蹤成效數據並提出優化建議","支援品牌行銷、課程招生、募資溝通、招募宣傳與競品趨勢整理"]'::jsonb,
      '["具社群行銷、內容企劃或品牌行銷經驗佳","文案能力清楚，具視覺品味、溝通協作能力與基本數據判讀能力","對長照、社會議題或服務品牌有熱情，能把專業內容轉成大眾看得懂的語言"]'::jsonb,
      '["內容月曆","跨部門素材","品牌行銷","數據優化"]'::jsonb,
      140,
      false,
      '2026-07-08 00:00:00+08'::timestamptz
    ),
    (
      'day-care-team',
      'taipei-day-care-director',
      '臺北市日間照顧中心主任（純白班、儲備主管職）',
      '中心主任',
      '負責日照中心營運、人員管理、招生社區關係、法規評鑑與服務品質，作為儲備主管培養。',
      '全職',
      '臺北市萬華區',
      '月薪 50,000 元以上',
      '1 名',
      '/assets/daycare-detail-04-checkin-fast.jpg',
      '["管理日照中心日常營運、照顧品質、招生推廣與社區關係","統籌跨專業團隊、人力招募訓練、預算、補助與行政流程","推動法規合規、評鑑、ISO、內部稽核、數據分析與危機客訴處理"]'::jsonb,
      '["具長照、社工、護理、老人照顧、公共衛生或中心管理經驗佳","熟悉日照法規、評鑑、補助、招生營運與跨專業團隊協作尤佳","能以主管視角處理人力、品質、家屬溝通與營運數據"]'::jsonb,
      '["純白班","儲備主管","營運培訓","月薪 5 萬以上"]'::jsonb,
      150,
      true,
      '2026-07-08 00:00:00+08'::timestamptz
    ),
    (
      'home-care-team',
      'new-taipei-home-care-supervisor',
      '新北市居家服務督導員（新店／中和／永和區）',
      '居服督導',
      '以保障薪資加業績獎金制度，負責新店、中和、永和居家服務個案管理、照服員督導與服務品質追蹤。',
      '全職',
      '新北市新店區',
      '月薪 38,000-42,000 元',
      '1-2 名',
      '/assets/recruit-home-care-supervisor-fast.jpg',
      '["管理服務安排、異動追蹤、家訪電訪與服務滿意度","督導照服員出勤、紀錄、服務品質與教育訓練需求","與照管中心、A 單位、家屬、個管師及跨專業資源協調"]'::jsonb,
      '["具居家服務督導資格、社工、護理或長照背景佳","熟悉長照 2.0、BA 碼、補助核銷、Word、Excel 或 Google Workspace","可配合新店、中和、永和區外勤、會議與教育訓練"]'::jsonb,
      '["保障月薪","業績獎金","快樂星期五","職涯培訓"]'::jsonb,
      160,
      true,
      '2026-07-07 00:00:00+08'::timestamptz
    ),
    (
      'home-care-team',
      'new-taipei-case-manager',
      '新北市個案管理師（新店區）',
      '個案管理',
      '負責 A 單位個案管理、照顧計畫、AA01/AA02 追蹤與跨資源溝通，協助家庭把服務安排變清楚。',
      '全職',
      '新北市新店區',
      '月薪 40,000-65,000 元',
      '1-2 名',
      '/assets/homepage-batch/family-consultation-clear.jpg',
      '["執行個案開案、需求評估、照顧計畫擬定、定期追蹤與紀錄","串接照管中心、居家服務、日照、復能、護理與家庭資源","整理系統資料、服務進度、品質指標與補助核銷相關紀錄"]'::jsonb,
      '["具 A 單位個案管理經驗或社工、護理、職能、物理治療、長照背景佳","熟悉長照 2.0、AA01/AA02、個案管理流程與系統紀錄尤佳","能獨立外勤訪視，並以清楚文字整理服務進度與家庭需求"]'::jsonb,
      '["保障月薪","AA 拆帳","年資加給","快樂星期五"]'::jsonb,
      170,
      true,
      '2026-07-09 00:00:00+08'::timestamptz
    )
),
upserted as (
  insert into public.recruiting_openings (
    page_slug,
    department_id,
    opening_slug,
    title,
    subtitle,
    summary,
    employment_type,
    location,
    salary_text,
    capacity_label,
    image_id,
    image_url,
    duties,
    requirements,
    benefits,
    apply_button_text,
    apply_form_enabled,
    metadata,
    sort_order,
    is_featured,
    is_enabled,
    status,
    published_at
  )
  select
    'talent',
    department.id,
    target.opening_slug,
    target.title,
    target.subtitle,
    target.summary,
    target.employment_type,
    target.location,
    target.salary_text,
    target.capacity_label,
    media.id,
    target.image_url,
    target.duties,
    target.requirements,
    target.benefits,
    '申請應徵',
    true,
    jsonb_build_object('form_type', 'recruiting', 'source', '104-company-page-2026-07-11'),
    target.sort_order,
    target.is_featured,
    true,
    'published',
    target.published_at
  from target_openings target
  join public.recruiting_departments department
    on department.page_slug = 'talent'
   and department.department_slug = target.department_slug
  left join public.media media
    on media.storage_path = regexp_replace(target.image_url, '^/', '')
  on conflict (page_slug, opening_slug) do update
  set department_id = excluded.department_id,
      title = excluded.title,
      subtitle = excluded.subtitle,
      summary = excluded.summary,
      employment_type = excluded.employment_type,
      location = excluded.location,
      salary_text = excluded.salary_text,
      capacity_label = excluded.capacity_label,
      image_id = excluded.image_id,
      image_url = excluded.image_url,
      duties = excluded.duties,
      requirements = excluded.requirements,
      benefits = excluded.benefits,
      apply_button_text = excluded.apply_button_text,
      apply_form_enabled = excluded.apply_form_enabled,
      metadata = public.recruiting_openings.metadata || excluded.metadata,
      sort_order = excluded.sort_order,
      is_featured = excluded.is_featured,
      is_enabled = true,
      status = 'published',
      published_at = excluded.published_at
  returning opening_slug
)
update public.recruiting_openings opening
set is_enabled = false,
    status = 'archived',
    is_featured = false,
    metadata = opening.metadata || jsonb_build_object('archived_reason', 'Replaced by current 104 talent openings on 2026-07-11')
where opening.page_slug = 'talent'
  and opening.opening_slug not in (select opening_slug from target_openings);
